[package]
name = "fi-slurm-limits"
version = "0.1.0"
edition = "2024"
license = "Apache-2.0"

[dependencies]
clap = { version = "4.5.40", features = ["derive"] }
fi-slurm = {path = "../fi-slurm"}
fi-slurm-db = {path = "../fi-slurm-db"}
users = "0.11.0"
