[package]
name = "fi-slurm-limits"
version = { workspace = true }
edition = { workspace = true }
license = { workspace = true }

[dependencies]
clap = { version = "4.5.40", features = ["derive"] }
fi-slurm = {path = "../fi-slurm"}
fi-slurm-db = {path = "../fi-slurm-db"}
users = "0.11.0"
