[package]
name = "fi_node"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.41"
clap = { version = "4.5.40", features = ["derive"] }
once_cell = "1.21.3"
regex = "1.11.1"
fi_slurm = {path = "../fi_slurm"}
colored = "3.0.0"
