[package]
name = "fi-node"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bindgen = "0.72.0"
clap = "4.5.40"
libc = "0.2.172"
