[workspace]
resolver = "2"

members = [
    "fi-job-top",
    "fi-limits",
    "fi-nodes",
    "fi-prometheus",
    "fi-slurm-bind",
    "fi-slurm-db",
    "fi-slurm",
]
default-members = [
    "fi-limits",
    "fi-nodes",
]
