[package]
name = "fi-slurm-db"
version = { workspace = true }
edition = { workspace = true }
build = "build.rs"
license = { workspace = true }

[dependencies]
bitflags = "2.9.1"
chrono = "0.4.41"
fi-slurm-bind = {path = "../fi-slurm-bind"}
thiserror = "2.0.12"
users = "0.11.0"
