[package]
name = "fi-prometheus"
version = { workspace = true }
edition = { workspace = true }
license = { workspace = true }

[dependencies]
chrono = "0.4.41"
reqwest = { version = "0.12.20", features = ["blocking"] }
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
