#include <stddef.h>
#include <slurm/slurm.h>

enum bind_node_state_flags {
    BIND_NODE_STATE_EXTERNAL = (1 << 4),
    BIND_NODE_STATE_RES = (1 << 5),
    BIND_NODE_STATE_UNDRAIN = (1 << 6),
    BIND_NODE_STATE_CLOUD = (1 << 7),
    BIND_NODE_STATE_RESUME = (1 << 8),
    BIND_NODE_STATE_DRAIN = (1 << 9),
    BIND_NODE_STATE_COMPLETING = (1 << 10),
    BIND_NODE_STATE_NO_RESPOND = (1 << 11),
    BIND_NODE_STATE_POWERED_DOWN = (1 << 12),
    BIND_NODE_STATE_FAIL = (1 << 13),
    BIND_NODE_STATE_POWERING_UP = (1 << 14),
    BIND_NODE_STATE_MAINT = (1 << 15),
    BIND_NODE_STATE_REBOOT_REQUESTED = (1 << 16),
    BIND_NODE_STATE_REBOOT_CANCEL = (1 << 17),
    BIND_NODE_STATE_POWERING_DOWN = (1 << 18),
    BIND_NODE_STATE_DYNAMIC_FUTURE = (1 << 19),
    BIND_NODE_STATE_REBOOT_ISSUED = (1 << 20),
    BIND_NODE_STATE_PLANNED = (1 << 21),
    BIND_NODE_STATE_INVALID_REG = (1 << 22),
    BIND_NODE_STATE_POWER_DOWN = (1 << 23),
    BIND_NODE_STATE_POWER_UP = (1 << 24),
    BIND_NODE_STATE_POWER_DRAIN = (1 << 25),
    BIND_NODE_STATE_DYNAMIC_NORM = (1 << 26),
    BIND_NODE_STATE_BLOCKED = (1 << 27)
};
