#include <stddef.h>
#include <slurm/slurm.h>
#include <slurm/slurmdb.h>

enum bind_node_state_flags {
    EXTERNAL = (1 << 4),
    RES = NODE_STATE_RES,
    UNDRAIN = NODE_STATE_UNDRAIN,
    CLOUD = NODE_STATE_CLOUD,
    RESUME = (1 << 8),
    DRAIN = NODE_STATE_DRAIN,
    COMPLETING = NODE_STATE_COMPLETING,
    NO_RESPOND = NODE_STATE_NO_RESPOND,
    POWERED_DOWN = NODE_STATE_POWERED_DOWN,
    FAIL = NODE_STATE_FAIL,
    POWERING_UP = NODE_STATE_POWERING_UP,
    MAINT = NODE_STATE_MAINT,
    REBOOT_REQUESTED = NODE_STATE_REBOOT_REQUESTED,
    REBOOT_CANCEL = NODE_STATE_REBOOT_CANCEL,
    POWERING_DOWN = NODE_STATE_POWERING_DOWN,
    DYNAMIC_FUTURE = NODE_STATE_DYNAMIC_FUTURE,
    REBOOT_ISSUED = NODE_STATE_REBOOT_ISSUED,
    PLANNED = NODE_STATE_PLANNED,
    INVALID_REG = NODE_STATE_INVALID_REG,
    POWER_DOWN = NODE_STATE_POWER_DOWN,
    POWER_UP = NODE_STATE_POWER_UP,
    POWER_DRAIN = NODE_STATE_POWER_DRAIN,
    DYNAMIC_NORM = NODE_STATE_DYNAMIC_NORM,
    BLOCKED = NODE_STATE_BLOCKED,
};
