[package]
name = "fi-slurm"
version = { workspace = true }
edition = { workspace = true }
build = "build.rs"
license = { workspace = true }

[dependencies]
bitflags = "2.9.1"
chrono = "0.4.41"
regex = "1.11.1"
fi-slurm-sys = {path = "../fi-slurm-sys"}
