[package]
name = "fi-slurm"
version = "0.1.0"
edition = "2024"
build = "build.rs"
license = "Apache-2.0"

[dependencies]
bitflags = "2.9.1"
chrono = "0.4.41"
regex = "1.11.1"
fi-slurm-bind = {path = "../fi-slurm-bind"}
