[package]
name = "fi_slurm_db"
version = "0.1.0"
edition = "2024"
build = "build.rs"

[dependencies]
bitflags = "2.9.1"
chrono = "0.4.41"
rust_bind = {path = "../rust_bind"}
thiserror = "2.0.12"
users = "0.11.0"
