name: Publish Binaries

on:
  release:
    types: [published]

jobs:
  build-and-attach:
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: x86_64-unknown-linux-gnu
            runs-on: ubuntu-latest
          - platform: x86_64-unknown-linux-musl
            runs-on: ubuntu-latest
          - platform: aarch64-unknown-linux-gnu
            runs-on: ubuntu-24.04-arm
          - platform: aarch64-unknown-linux-musl
            runs-on: ubuntu-24.04-arm
    runs-on: ${{ matrix.runs-on }}
    steps:
      - uses: actions/checkout@v4

      - name: Install targets
        run: |
          rustup target add ${{ matrix.platform }}

      - name: Build
        run: |
          cargo build --release --target ${{ matrix.platform }}
      
      - name: Upload as release asset
        run: |
          cd target/${{ matrix.platform }}/release
          name="cephdu-${{ github.event.release.tag_name }}-${{ matrix.platform }}"
          mv cephdu $name
          gh release upload "${{ github.event.release.tag_name }}" $name
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
